[project]
name = "reddit-consumer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "pika>=1.3.2",
    "pymongo>=4.14.0",
    "requests>=2.32.3",
]
